- name: Start firewalld
  service: name=firewalld state=started enabled=yes
  tags: Start firewalld

- name: Insert firewalld rule for httpd
  firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes
  tags: Enable httpd port

- name: insert firewalld rule for mysql
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
  tags: Enable mysql port

- name: http service state
  service: name=httpd state=started enabled=yes
  tags: httpd start